# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]

[default.build.parameters]
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "sam-lambdas-deployment-stack"
region = "eu-west-1"
s3_bucket = "sam-lambdas-deployment-bucket"
capabilities = "CAPABILITY_IAM"

[default.package.parameters]
region = "eu-west-1"
s3_bucket = "sam-lambdas-deployment-bucket"

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
